// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGKB8yjbTyIXgPZXmNly7uUHL5Palu00',
    appId: '1:709056935190:web:445a2117b45e8ffa844c37',
    messagingSenderId: '709056935190',
    projectId: 'hermes-kids',
    authDomain: 'hermes-kids.firebaseapp.com',
    storageBucket: 'hermes-kids.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPSHUzeQegDjFHw-jjRS5cDMgT14odVlM',
    appId: '1:709056935190:android:3820765feaaa54c3844c37',
    messagingSenderId: '709056935190',
    projectId: 'hermes-kids',
    storageBucket: 'hermes-kids.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ_5YxdTebV_h18GqSTm0zs9cDa-OKfM4',
    appId: '1:709056935190:ios:c83ce796695ef482844c37',
    messagingSenderId: '709056935190',
    projectId: 'hermes-kids',
    storageBucket: 'hermes-kids.appspot.com',
    iosClientId: '709056935190-c62s2fjtaug8jkc8kd4shfbf8ndb88fb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hermesKids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ_5YxdTebV_h18GqSTm0zs9cDa-OKfM4',
    appId: '1:709056935190:ios:9e0433d25e969d01844c37',
    messagingSenderId: '709056935190',
    projectId: 'hermes-kids',
    storageBucket: 'hermes-kids.appspot.com',
    iosClientId: '709056935190-gssmlngsvn470r1o80vm9gkprj204omn.apps.googleusercontent.com',
    iosBundleId: 'com.example.hermesKids.RunnerTests',
  );
}
